### ISSUE TITLE
Signal doesn't run, at all

### ISSUE THREAD

**Issue by ghost** [drahnr/signal-desktop-rpm#1]
I am unsure as to whether I should post this on Signal's own repository or here, for you - as you can notice, I'm newbie when it comes to bugs and debugging...

I used to run this .rpm Signal through your repository a couple of months ago when I first found it. All of a sudden, it didn't launch at all when I clicked it on my menu (Fedora 28 Xfce.) I decided to ditch it and did sudo dnf remove signal-desktop.

Today I decided to give it another chance with a more up-to-date package as I noticed you updated the version 22 days ago. Same result: when I tap on it, nothing happens. I proceeded to run signal-desktop on terminal and this is the output:

**signal-desktop-1.15.4-1.fc28.x86_64**

`NODE_ENV production
NODE_CONFIG_DIR /usr/lib64/signal-desktop/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
userData: /home/rottensox/.config/Signal
making app single instance
{"name":"log","hostname":"rottensox","pid":7343,"level":30,"msg":"app ready","time":"2018-09-06T21:22:03.834Z","v":0}
{"name":"log","hostname":"rottensox","pid":7343,"level":30,"msg":"Ensure attachments directory exists","time":"2018-09-06T21:22:03.843Z","v":0}
{"name":"log","hostname":"rottensox","pid":7343,"level":30,"msg":"updateSchema: Current schema version: 0; Most recent schema version: 3; SQLite version: 3.20.1; SQLCipher version: 3.4.2;","time":"2018-09-06T21:22:03.849Z","v":0}
{"name":"log","hostname":"rottensox","pid":7343,"level":30,"msg":"updateToSchemaVersion1: starting...","time":"2018-09-06T21:22:03.850Z","v":0}
Segmentation fault (core dumped)
`

If this is not an issue of packaging, could you please give me orientation - link of the issues repository and how to get more logs if necessary, please?

**Comment by drahnr** [comment]
I am aware of this but basically the linked version of openssl (which is older than fedoras) is linked but not available which results in this. As soon as a upstream release is done or a viable workaround for packaging (without forking the project) is found I'll update this repo (the rest will happen automatically i.e. publish of a new rpm).

**Comment by drahnr** [comment]
Just tried 1.16.0 but with no succes. I am happy to get a PR with a workaround using the system openssl instead of the inbuilt.

If you installed via copr, you can downgrade to `signal-desktop-1.14.4-1.fc28.x86_64` - which is the last version. You can build that from the git tag (which I just created + pushed).

For upstream tickets, there are a few:
https://github.com/signalapp/Signal-Desktop/issues/2662
https://github.com/signalapp/Signal-Desktop/issues/2634

**Comment by ghost** [comment]
I believe it's best if you do the PR with a workaround, though. We don't seem to be getting too much attention from Signal developers, do we?

**Comment by drahnr** [comment]
I wrote an e-mail to scott as he requested in the last ticket I created. Until then this is unfortunately on hold.

**Comment by ghost** [comment]
We might have news or a workaround: https://github.com/signalapp/Signal-Desktop/issues/2662

**Comment by drahnr** [comment]
I have a working f29 locally, I just need to fix the ci pipeline to start distributing it. I am afraid it might require upgrade to f29 since it relies on `dnf module` support for `nodejs`. I read the linked solution but I am not quite sure it solves all building problems though, I have yet to try. I am happy to see a PR :)

**Comment by ghost** [comment]
Failed to synchronize cache for repo 'drahnr-signal-desktop', ignoring this repo.

Already on F29 and awaiting for Signal to work again. Keep us posted on what to do next! Thanks for following up.

**Comment by drahnr** [comment]
I created a manual release for the time being https://github.com/drahnr/signal-desktop-rpm/releases/tag/v1.17.2 - to install please disable the copr repo for the time being until I figured that out.

See #1 for discussion.

**Comment by ghost** [comment]
I've `sudo dnf remove signal-desktop` and proceeded with the manual install of the provided .rpm package - it works great thus far. Will do further testing.

I have two signal-related files at `/etc/yum.repos.d`: _drahnr-signal-desktop-fedora-28.repo_ and _signal-desktop-rpm_.

Drahnr's content:

[drahnr-signal-desktop]
name=Copr repo for signal-desktop owned by drahnr
baseurl=https://copr-be.cloud.fedoraproject.org/results/drahnr/signal-desktop/fedora-$releasever-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/drahnr/signal-desktop/pubkey.gpg
repo_gpgcheck=0
enabled=0
enabled_metadata=1

Signal's content:

[drahnr-signal-desktop]
name=Copr repo for signal-desktop owned by drahnr
baseurl=https://copr-be.cloud.fedoraproject.org/results/drahnr/signal-desktop/fedora-$releasever-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/drahnr/signal-desktop/pubkey.gpg
repo_gpgcheck=0
enabled=0
enabled_metadata=1

Should I get rid of one? They look like they're the same. I've changed the 1 to 0 on the enabled value as per your request, for the time being...

**Comment by drahnr** [comment]
Just disable/delete all of them or use `dnf copr disable drahnr/signal-desktop` (or maybe `remove`)

**Comment by ghost** [comment]
Will I need both in the future when it gets fixed or I can keep just one? That's my main question, if you don't mind.

On F29 I seem to have a problem closing programs. The program seems to be gone but the window stays there and there's no way I can get rid of it at all. It happened with Signal also (I close it and the window gets frozen at the last state with no chance for me to get past it.) The system said Signal wasn't responding and asking me whether I wanted to shut it down or not, I agreed but it was still there.

How can I help debug this? It's F29 + Xfce. ./signal-desktop may help to fetch a log, right? But since I manually installed the .rpm, where should I execute the command? (Path.)

It is strictly an UI issue, I'd have to say: the frozen window is still there, I tried to reopen, see the messages coming through but cannot open the application, at all.

**Comment by drahnr** [comment]
Nothing I can do here, so closing for now.
