### ISSUE TITLE
1.20 and newer don't work on fedora 29

### ISSUE THREAD

**Issue by lsm5** [drahnr/signal-desktop-rpm#4]
Hi, thanks for releasing newer builds of signal-desktop, but running versions 1.20 and newer give me the `No such module: fts5`. 1.19 works just fine.

Also, the copr repo doesn't seem to fetch anything.

**Comment by drahnr** [comment]
See #2, I also did a few attempts on fixing the build, without first creating and extracting a rpm via yarn, but os far no success (see a321afaab85ad602c23eab42304723dbbbf36b1a and up)

**Comment by drahnr** [comment]
#2 got resolved, feel free to reopen if the issue persists
