### ISSUE TITLE
Where to fetch negativo's .rpm?

### ISSUE THREAD

**Issue by ghost** [drahnr/signal-desktop-rpm#6]
Sorry to bug you with this probably stupid question. I was getting the .rpm files from @sirmergealot at https://github.com/drahnr/signal-desktop-rpm/releases. I believe last couple of releases weren't working though. I see you've deprecated this repository and directed people to https://github.com/negativo17/Signal-Desktop but I do not see any package I could work with. Could you give me pointers on how to make it work, please? I'd ideally also want to check the current signal version I am running and hoping it doesn't get deleted from your releases section so that I can have the .rpm in hand, should @negativo17's not work either. Thanks!

**Comment by drahnr** [comment]
It is enough to enable `https://negativo17.org/multimedia/` for your machine, afterwards you'll find it via `dnf config-manager --add-repo=https://negativo17.org/repos/fedora-multimedia.repo && dnf install Signal-Desktop.x86_64` works. If you have any further questions, feel free!
